default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: dj_web_development

test:
  <<: *default
  database: dj_web_test